const Fazendinha = {
  name: 'Espaço Agro',
  description: 'Secretaria de Agricultura e Pesca',
  URLImg: '../img/Fazendinha/agro-thumb.png',
  atracoes: [
    {
      name: 'DIA 05',
      data: '5',
      description: 'Data do show: 05 de julho',
      icon: '',
      URLImg: '',
      hora1: '13:00h',
      hora2: '14:00h',
      hora3: '15:00h',
      hora4: '17:00h',
      at1: 'MÚSICA AO VIVO (PALCO AGRO)',
      at2: 'OFICINA - Reaproveitamento integral dos produtos (AGRO COZINHA)',
      at3: 'OFICINA - Produção de Própolis (CASA DO MEL)',
      at4: 'MÚSICA AO VIVO (PALCO AGRO)',
      at5: 'OFICINA - MELIPONICULTURA - Criação e manejo de abelhas sem ferrão',
      at6: 'PALESTRA - Boas práticas de fabricação na manipulação dos alimentos - Embrapa (CASA DE PNEUS)',
      at7: 'OFICINA - Cultivo de temperos, plantas aromáticas e medicinas em sist. Orgânico (ESPAÇO AGRO SABER)',
      at8: '--',
      at9: 'OFICINA - Controle de pequeno besouro das colmeias (CASA DO MEL)',
      at10: '--',
      at11: 'GINCANA - Gincana Cainina I (ESPAÇO PET)',
      at12: '--',
      at13: '--',
      at14: '--',
      at15: 'OFICINA - Bananas em caldas (AGRO COZINHA)',
      at16: '--',
      at17: '--',
      at18: '--',
      at19: 'PALESTRA - PRocessamento mínimo de frutas - Embrapa (CASA DE PNEUS)',
      at20: '--',
    },
    {
      name: 'DIA 06',
      data: '6',
      description: 'Data do show: 05 de julho',
      icon: '',
      URLImg: '',
      hora1: '15:00h',
      hora2: '17:00h',
      hora3: '19:00h',
      at1: 'PALESTRA - Experiência dos alimentos biofortificados em Itaguaí - Embrapa (CASA DE PNEUS)',
      at2: 'OFICINA - Artesanato com folhas de coqueiro (ESPAÇO SABER)',
      at3: 'MÚSICA AO VIVO (PALCO AGRO)',
      at4: '',
      at5: 'WORKSHOP - Artesanato com palha de bananeira (ESPAÇO AGRO SABER)',
      at6: '--',
      at7: '--',
      at8: '',
      at9: 'OFICINA - Produção de sorvete artesanal (AGRO COZINHA)',
      at10: '--',
      at11: '--',
      at12: '',
      at13: '--',
      at14: '--',
      at15: '--',
      at16: '',
      at17: '--',
      at18: '--',
      at19: '--',
      at20: '',
    },
    {
      name: 'DIA 07',
      data: '7',
      description: 'Data do show: 05 de julho',
      hora1: '13:00h',
      hora2: '15:00h',
      hora3: '18:00h',
      hora4: '19:00h',
      at1: 'OFICINA - Confecção de bijuterias com escama de peixe (ESPAÇO SABER)',
      at2: 'WORKSHOPP - Artesanato com conchas de vieira  (ESPAÇO AGRO SABER)-',
      at3: 'PALESTRA - Manejo e manipulação de ovo (CASA DE PNEUS)',
      at4: 'MÚSICA AO VIVO (PALCO AGRO)',
      at5: 'OFICINA - Sobre Edamame (AGRO COZINHA)',
      at6: '--',
      at7: '--',
      at8: '--',
      at9: '--',
      at10: '--',
      at11: '--',
      at12: '--',
      at13: '--',
      at14: '--',
      at15: '--',
      at16: '--',
      at17: '--',
      at18: '--',
      at19: '--',
      at20: '--',
    },
    {
      name: 'DIA 08',
      data: '8',
      description: 'Data do show: 05 de julho',
      hora1: '14:00h',
      hora2: '15:00h',
      hora3: '16:00h',
      hora4: '17:00h',
      hora5: '19:00h',
      at1: 'OFICINA - Fabricação de pão de queijo (AGRO COZINHA)',
      at2: '-OFICINA - Pomada natural medicinal cicatrizante (AGRO COZINHA)-',
      at3: 'PALESTRA - Nota fiscal e insenção do ICMS da luz - Sindicato Rural (CASA PNEUS)',
      at4: '-OFICINA - Prato decorativo com casca de ovo (ESPAÇO SABER)-',
      at5: '--',
      at6: 'GINCANA - Gicana Canina II (ESPAÇO PET)',
      at7: '--',
      at8: '--',
      at9: '--',
      at10: '--',
      at11: '--',
      at12: '--',
      at13: '--',
      at14: '--',
      at15: '--',
      at16: '--',
      at17: '--',
      at18: '--',
      at19: '--',
      at20: '--',
      at21: '-MÚSICA AO VIVO (PALCO AGRO)-',
      at22: '--',
      at23: '--',
      at24: '--',
    },
    {
      name: 'DIA 09',
      data: '9',
      description: 'Data do show: 05 de julho',
      hora1: '13:00h',
      hora2: '15:00h',
      hora3: '16:00h',
      hora4: '17:00h',
      hora5: '19:00h',
      at1: 'OFICINA - Artesanato com folha de coqueiro II (ESPAÇO SABER)',
      at2: 'OFICINA - Bijuterias com sementes de açai (ESPAÇO SABER)',
      at3: 'PALESTRA - Segurado especial - Sindicato Rural (CASA DE PNEUS)',
      at4: 'OFICINA - Artesanato com folhas de coqueiro (ESPAÇO SABER)',
      at5: '--',
      at6: 'OFICINA - Bolinho de massa de abóbora com carne seca (AGRO COZINHA)',
      at7: '--',
      at8: '--',
      at9: '--',
      at10: 'GINCANA - Gincana Caninina III (ESPAÇO PET)',
      at11: '--',
      at12: '--',
      at13: '--',
      at14: '--',
      at15: '--',
      at16: '--',
      at17: '--',
      at18: '--',
      at19: '--',
      at20: '--',
      at21: 'MÚSICA AO VIVO (PALCO AGRO)',
      at22: '--',
      at23: '--',
      at24: '--',
    },
  ]
}

export default Fazendinha